base_url = "https://shixiaocaia.github.io"
title = "shixiaocaia"
description = "星际穿梭"
compile_sass = true
build_search_index = false
generate_feed = true
default_language = "en"
theme = "willow"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
render_emoji = true


[languages.en.translations]
language_name = "English"
home = "Home"
posts = "Posts"
tags = "Tags"
photography = "Photography"
about = "About"
memos = "Status"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[languages.zh-CN.translations]
language_name = "中文"
home = "首页"
posts = "文章"
tags = "标签"
photography = "摄影"
about = "关于"
memos = "碎碎念"
date_format = "%Y-%m-%d"
next_page = "下一页"
last_page = "上一页"


[extra]


# --- willow config example --- #

[extra.willow]
# The number of articles to show on the home page
show_article_num = 10

# The order of the navigation bar, home is the first by default
# current supported nav: articles, tags, about, photography, memos
nav = ["posts", "photography", "about"]

# Google analytics ID
google_analytics = "G-XDREGKCZH0"


# --- social accounts --- #
# currently supported: twitter, douban, github

[extra.willow.social]
douban = "227565842"
github = "shixiaocaia"

# --- photography --- #

[extra.willow.photography]

# if not set, will use photos from config below
type = "unsplash"

# unsplash client id, you need to apply developer account on unsplash
unsplash_client_id = "kXlp6O1lnJmY5l5YhjasuOiRlYjxQhcduihCAUjveFA"
# unsplash author
unsplash_author = "shixiaocaia"

# Put the photos you want to show on the photography page here
photos = [
    "https://file.chaojie.fun/photography/过春天.jpg",
]



