# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - on: push
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark static sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: book
        format: csv
        dir: ./data/douban
        
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban static'
        add: './data/douban'