# .github/workflows/douban.yml
name: douban
on: 
  schedule: # 自动运行workflow
    - cron: '30 5 * * 1' # 每到整点运行一次
  workflow_dispatch: # 可以手动在仓库的action中运行workflow

jobs:
  douban:
    name: Douban mark static sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: book
        format: csv
        dir: ./data/douban
        
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban static'
        add: './data/douban'