# .github/workflows/douban.yml
name: douban
on:
  push:
    branches:
      - master   //当master分支更新时执行
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: movie
        format: csv
        dir: ./data/douban    //数据保存在data/douban文件夹

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 227565842
        type: book
        format: csv
        dir: ./data/douban  
        
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'    //提交到data/douban文件夹